on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: aarch64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and publish
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
